const INCREMENT_CURRENT_TIME = '@player/INCREMENT_CURRENT_TIME';
const SET_ACTIVE = '@player/SET_ACTIVE';
const SET_CURRENT_TIME = '@player/SET_CURRENT_TIME';
const SET_STARTED_PLAYING = '@player/SET_STARTED_PLAYING';
const TOGGLE_PLAY = '@player/TOGGLE_PLAY';

export const Actions = {
  INCREMENT_CURRENT_TIME,
  SET_ACTIVE,
  SET_CURRENT_TIME,
  SET_STARTED_PLAYING,
  TOGGLE_PLAY,
};
