const INCREMENT_CURRENT_TIME = '@player/INCREMENT_CURRENT_TIME';
const SET_ACTIVE = '@player/SET_ACTIVE';
const SET_AUDIO = '@player/SET_AUDIO';
const SET_INTERVAL_ID = '@player/SET_INTERVAL_ID';
const SET_CURRENT_TIME = '@player/SET_CURRENT_TIME';
const SET_STARTED_PLAYING = '@player/SET_STARTED_PLAYING';
const TOGGLE_PLAY = '@player/TOGGLE_PLAY';
const ADD_TO_HISTORY = '@player/ADD_TO_HISTORY';
const ADD_COMMENTARY_TO_ACTIVE = '@player/ADD_COMMENTARY_TO_ACTIVE';

export const Actions = {
  ADD_COMMENTARY_TO_ACTIVE,
  ADD_TO_HISTORY,
  INCREMENT_CURRENT_TIME,
  SET_ACTIVE,
  SET_AUDIO,
  SET_INTERVAL_ID,
  SET_CURRENT_TIME,
  SET_STARTED_PLAYING,
  TOGGLE_PLAY,
};
