const REQUEST_PODCAST = '@podcast/REQUEST_PODCAST';
const REQUEST_RECOMMENDED = '@podcast/REQUEST_RECOMMENDED';
const SET_RECOMMENDED = '@podcast/SET_RECOMMENDED';
const SET_CURRENT = '@podcast/SET_CURRENT';
const REQUEST_RECENTLY_ADDED = '@podcast/REQUEST_RECENTLY_ADDED';
const SET_RECENTLY_ADDED = '@podcast/SET_RECENTLY_ADDED';

export const Actions = {
  REQUEST_PODCAST,
  REQUEST_RECOMMENDED,
  REQUEST_RECENTLY_ADDED,
  SET_CURRENT,
  SET_RECOMMENDED,
  SET_RECENTLY_ADDED,
};
