const REQUEST_PODCAST = '@podcast/REQUEST_PODCAST';
const REQUEST_RECOMMENDED = '@podcast/REQUEST_RECOMMENDED';
const SET_RECOMMENDED = '@podcast/SET_RECOMMENDED';
const SET_CURRENT = '@podcast/SET_CURRENT';
const REQUEST_RECENTLY_ADDED = '@podcast/REQUEST_RECENTLY_ADDED';
const SET_RECENTLY_ADDED = '@podcast/SET_RECENTLY_ADDED';
const ADD_COMMENTARY_TO_CURRENT_EPISODE =
  '@podcast/ADD_COMMENTARY_TO_CURRENT_EPISODE';
const FOLLOW_OR_UNFOLLOW = '@podcast/FOLLOW_OR_UNFOLLOW';
const REQUEST_FOLLOWING = '@podcast/REQUEST_FOLLOWING';
const SET_FOLLOWING = '@podcast/SET_FOLLOWING';

export const Actions = {
  REQUEST_PODCAST,
  REQUEST_RECOMMENDED,
  REQUEST_RECENTLY_ADDED,
  SET_CURRENT,
  SET_RECOMMENDED,
  SET_RECENTLY_ADDED,
  ADD_COMMENTARY_TO_CURRENT_EPISODE,
  FOLLOW_OR_UNFOLLOW,
  REQUEST_FOLLOWING,
  SET_FOLLOWING,
};
